### ISSUE TITLE
D3D_FEATURE_LEVEL_UNKNOWN is shows instead of D3D_FEATURE_LEVEL_12_2

### ISSUE THREAD

**Issue by Devaniti** [microsoft/DxCapsViewer#12]
On 2080ti D3D_FEATURE_LEVEL_UNKNOWN is shown instead of correct value.
Version [release feb2021](https://github.com/microsoft/DxCapsViewer/releases/tag/feb2021)
![image](https://user-images.githubusercontent.com/16295437/143478998-7a6c33de-998d-44ad-92eb-41241b1e456d.png)

**Comment by walbourn** [comment]
Did you build this locally or did you download the EXE?

**Comment by walbourn** [comment]
Nevermind, this was fixed in this commit but it missed the "Windows 11 SDK (22000)" cut-off.

https://github.com/microsoft/DxCapsViewer/commit/6437a77e4bcd8e276e9c42e4802f0a4cf9913de6

The fix will be in the next release of the Windows SDK and is currently in insider builds.
