### ISSUE TITLE
Feature request: D3D12_RENDER_PASS_TIER output

### ISSUE THREAD

**Issue by Devaniti** [microsoft/DxCapsViewer#13]
There's currently no way to see support tier for render passes.

**Comment by walbourn** [comment]
This is from ``D3D12_FEATURE_DATA_D3D12_OPTIONS5``:

```
D3D12_RENDER_PASS_TIER_0	= 0,
D3D12_RENDER_PASS_TIER_1	= 1,
D3D12_RENDER_PASS_TIER_2	= 2
```

**Comment by walbourn** [comment]
This was added in this commit:

https://github.com/microsoft/DxCapsViewer/commit/baa406060815b6fd76f8e1cf3585f57c88ee3c13

This was in the *Windows 10 SDK (20348), version 2104* SDK and is in the Windows 11 SDK (22000) as well.
