### ISSUE TITLE
Add D3D12_FEATURE_DATA_D3D12_OPTIONS8::UnalignedBlockTexturesSupported

### ISSUE THREAD

**Issue by AdamJMiles** [microsoft/DxCapsViewer#19]
This seems to be missing, despite newer "OPTIONS" (e.g. 9) being check and reported.

Adam

**Comment by walbourn** [comment]
Thanks.  Missed that one.

**Comment by walbourn** [comment]
Thanks!

https://github.com/microsoft/DxCapsViewer/commit/54b411ed26c7ba7bf4444c9ddc61457c2c36f88f
