### ISSUE TITLE
Request support for Agility SDK 1.614.1

### ISSUE THREAD

**Issue by Demonese** [microsoft/DxCapsViewer#22]
The new version of SDK brings some interesting features.

**Comment by walbourn** [comment]
Specific types to add are:

* D3D_ROOT_SIGNATURE_VERSION_1_2
* D3D12_OPTIONS16.GPUUploadHeapSupported, D3D12_OPTIONS17, D3D12_OPTIONS18, D3D12_OPTIONS19

**Comment by walbourn** [comment]
Added to add OPTION18, 19 stuff still.
