### ISSUE TITLE
Spelling error Variable Rate Shading (VRS) entry

### ISSUE THREAD

**Issue by gschroecker** [microsoft/DxCapsViewer#8]
I love that DxCapsViewer is now available on GitHub. I found a small spelling error:
"Tier" is misspelled as "Teir" for the Variable Rate Shading (VRS) entry. See also screenshot.

![DxCapsViewerBug](https://user-images.githubusercontent.com/316358/120003250-db1d4580-bfd5-11eb-92ac-d79ab545e7a7.png)

**Comment by walbourn** [comment]
Thanks for the report.

Fixed in this commit: https://github.com/microsoft/DxCapsViewer/commit/396dc45d7b72691288b9fe3b09af769c95062b71
